name: apps_list
description: A Flutter package for listing and launching Android apps across multiple profiles.
version: 0.0.3
homepage: https://github.com/kelvinkipruto/app_list
repository: https://github.com/kelvinkipruto/app_list

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.3

flutter:
  plugin:
    platforms:
      android:
        package: dev.kipruto.apps_list
        pluginClass: AppsListPlugin

